name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    strategy:
      matrix:
        image:
        - context: linux
          name: prebuild-linux
          platforms: |
            linux/amd64
            linux/arm64
        - context: alpine
          name: prebuild-alpine
          platforms: |
            linux/amd64
            linux/arm64
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}
      - uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image.context }}
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
